name: 'clang-format'
description: 'Run clang-format on pull request'
runs:
  using: "composite"
  steps:
  - name: Run clang-format for the patch
    shell: bash {0}
    run: |
      git config --global --add safe.directory /__w/llvm/llvm
      git fetch origin ${{ github.event.pull_request.base.ref }}
      #git merge origin/sycl --no-commit || exit 1
      #echo ${GITHUB_SHA} ${{ github.event.pull_request.commits }}
      #git diff ${GITHUB_SHA} HEAD
      #git show HEAD
      #git show HEAD^1
      #git show HEAD^2
      #git diff HEAD^2 HEAD
      git clang-format -v ${GITHUB_SHA}
      git diff > ./clang-format.patch
  # Add patch with formatting fixes to CI job artifacts
  - uses: actions/upload-artifact@v1
    with:
      name: clang-format-patch
      path: ./clang-format.patch
  - name: Check if clang-format patch is empty
    shell: bash
    run: bash -c "if [ -s ./clang-format.patch ]; then cat ./clang-format.patch; exit 1; fi"
