name: aws-ec2
description: Starts AWS EC2 spot instance with github actions runner agent in it to process one job

inputs:
  label:
    description: Name of the unique label assigned to the runner used as 'runs-on' property for the following jobs
    required: true
  GH_PERSONAL_ACCESS_TOKEN:
    description: Github personal access token with repo permission
    required: true
  AWS_ACCESS_KEY:
    description: AWS access id
    required: true
  AWS_SECRET_KEY:
    description: AWS access secret key
    required: true
  aws-region:
    description: AWS EC2 region
    required: false
    default: "us-east-2" # Ohio
  aws-ami:
    description: AWS AMI id
    required: false
    default: "ami-0966bccbb521ccb24" # Ubuntu 22.04 (ami-02f3416038bdb17fb with /dev/sda1 disk) with docker installed and gh_runner (1001) like this:
    # sudo -s
    # apt-get update
    # curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    # sh /tmp/get-docker.sh # or "yum install -y docker" for Amazon Linux or RHEL/CentOS
    # groupadd -g 1001 gh_runner; useradd gh_runner -u 1001 -g 1001 -m -s /bin/bash; usermod -aG docker gh_runner; usermod -aG video gh_runner
    # sync; shutdown -h now
    
    # "ami-02ec0f344128253f9" # Amazon Linux 2 AMI with NVIDIA TESLA GPU Driver (ami-06bf0a3f89fe08f0a with /dev/xvda disk) with docker installed and gh_runner (1001) like this:
    # sudo -s
    # yum update -y
    # amazon-linux-extras install docker
    # sudo systemctl --now enable docker
    # distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.repo | sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo
    # yum-config-manager --disable amzn2-graphics; yum clean expire-cache; yum install -y nvidia-docker2; systemctl restart docker
    # groupadd -g 1001 gh_runner; useradd gh_runner -u 1001 -g 1001 -m -s /bin/bash; usermod -aG docker gh_runner; usermod -aG video gh_runner
    # sync; shutdown -h now
    
    # "ami-0ccda708841dde988" # Amazon Linux 2 AMI with AMD Radeon Pro Driver (ami-0bb1072e787242eb6 with /dev/xvda disk) with docker installed and gh_runner (1001) like this:
    # sudo -s
    # sh ./get-docker.sh # or "yum install -y docker" for Amazon Linux or RHEL/CentOS
    # amazon-linux-extras install docker
    # sudo systemctl --now enable docker
    # groupadd -g 1001 gh_runner; useradd gh_runner -u 1001 -g 1001 -m -s /bin/bash; usermod -aG docker gh_runner; usermod -aG video gh_runner
    # sync; shutdown -h now

  aws-type:
    description: AWS EC2 instance type
    required: false
    default: "t2.micro"
    # g4dn.xlarge: 1 NVIDIA T4 GPU, 4 CPU, 16 GB RAM 
    # g4ad.2xlarge: 1 AMD Radeon Pro V520 GPU, 8 CPU, 32 GB RAM (limited avaiability for g4ad.xlarge)
  aws-disk:
    description: AWS EC2 instance AMI specific disk device path and size in GB (8 by default)
    required: false
    default: "/dev/sda1:16" # Github actions container engine will fail with lack of disk space for 8GB
  aws-timebomb:
    description: AWS EC2 instance maximum live time
    required: false
    default: 1h

  mode:
    description: "Mode of operation: start or stop"
    required: false
    default: start
 
outputs:
  label:
    description: Name of the unique label assigned to the runner used as 'runs-on' property for the following jobs
    
runs:
  using: node12
  main: ./aws-ec2.js
